services:
  traefik:
    image: traefik:v3.1
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      #- "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      #- "--certificatesresolvers.myresolver.acme.email=joonas.o.tuominen@gmail.com"
      #- "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.http.redirections.entrypoint.to=web"      # Change these when we get TLS working
      - "--entrypoints.websecure.http.redirections.entrypoint.scheme=http" # ...
      #- "--entrypoints.web.http.redirections.entrypoint.to=websecure"     # to these
      #- "--entrypoints.web.http.redirections.entrypoint.scheme=https"     # ...
    ports:
      - mode: host
        protocol: tcp
        published: 80
        target: 80
      - mode: host
        protocol: tcp
        published: 443
        target: 443
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock

  web:
    image: webgl-app:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.web.loadbalancer.server.port=80"
      - "traefik.http.routers.web.rule=Host(`localhost`)"
      - "traefik.http.routers.web.entrypoints=web"
    #ports:   # Use these for testing
    #  - mode: host
    #    published: 4200
    #    target: 80

volumes:
  letsencrypt: